const cardDeck = [
  { name: "hearts_2.png", value: 2 },
  { name: "hearts_3.png", value: 3 },
  { name: "hearts_4.png", value: 4 },
  { name: "hearts_5.png", value: 5 },
  { name: "hearts_6.png", value: 6 },
  { name: "hearts_7.png", value: 7 },
  { name: "hearts_8.png", value: 8 },
  { name: "hearts_9.png", value: 9 },
  { name: "hearts_10.png", value: 10 },
  { name: "hearts_J.png", value: 10 },
  { name: "hearts_Q.png", value: 10 },
  { name: "hearts_K.png", value: 10 },
  { name: "hearts_A.png", value: 11 },

  { name: "clubs_2.png", value: 2 },
  { name: "clubs_3.png", value: 3 },
  { name: "clubs_4.png", value: 4 },
  { name: "clubs_5.png", value: 5 },
  { name: "clubs_6.png", value: 6 },
  { name: "clubs_7.png", value: 7 },
  { name: "clubs_8.png", value: 8 },
  { name: "clubs_9.png", value: 9 },
  { name: "clubs_10.png", value: 10 },
  { name: "clubs_J.png", value: 10 },
  { name: "clubs_Q.png", value: 10 },
  { name: "clubs_K.png", value: 10 },
  { name: "clubs_A.png", value: 11 },

  { name: "diamonds_2.png", value: 2 },
  { name: "diamonds_3.png", value: 3 },
  { name: "diamonds_4.png", value: 4 },
  { name: "diamonds_5.png", value: 5 },
  { name: "diamonds_6.png", value: 6 },
  { name: "diamonds_7.png", value: 7 },
  { name: "diamonds_8.png", value: 8 },
  { name: "diamonds_9.png", value: 9 },
  { name: "diamonds_10.png", value: 10 },
  { name: "diamonds_J.png", value: 10 },
  { name: "diamonds_Q.png", value: 10 },
  { name: "diamonds_K.png", value: 10 },
  { name: "diamonds_A.png", value: 11 },

  { name: "spades_2.png", value: 2 },
  { name: "spades_3.png", value: 3 },
  { name: "spades_4.png", value: 4 },
  { name: "spades_5.png", value: 5 },
  { name: "spades_6.png", value: 6 },
  { name: "spades_7.png", value: 7 },
  { name: "spades_8.png", value: 8 },
  { name: "spades_9.png", value: 9 },
  { name: "spades_10.png", value: 10 },
  { name: "spades_J.png", value: 10 },
  { name: "spades_Q.png", value: 10 },
  { name: "spades_K.png", value: 10 },
  { name: "spades_A.png", value: 11 },

  { name: "back_dark.png", value: 0 },
  { name: "back_light.png", value: 0 },
];

console.log(cardDeck[0].name);
